language: node_js
before_install:
  - sudo apt-get install libgif-dev gdebi-core
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo gdebi --non-interactive google-chrome-stable_current_amd64.deb
  - sudo chmod 1777 /dev/shm
  - export CHROME_SANDBOX=/opt/google/chrome/chrome-sandbox
  - sudo rm -f $CHROME_SANDBOX
  - sudo wget https://googledrive.com/host/0B5VlNZ_Rvdw6NTJoZDBSVy1ZdkE -O $CHROME_SANDBOX
  - sudo chown root:root $CHROME_SANDBOX; sudo chmod 4755 $CHROME_SANDBOX
  - sudo md5sum $CHROME_SANDBOX
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
node_js:
  - "0.10"
addons:
  firefox: "29.0"
script: "make ci"
after_script:
  - make coverage

