language: node_js
before_install:
  - sudo apt-get install libgif-dev
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
node_js:
  - 1.8.7
script: "make ci"
after_script:
  - make coverage

