language: node_js
addons:
  apt:
    packages:
      - libgif-dev
      - gdebi-core
  firefox: "29.0"
before_install:
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - gdebi --non-interactive google-chrome-stable_current_amd64.deb
  - chmod 1777 /dev/shm
  - export CHROME_SANDBOX=/opt/google/chrome/chrome-sandbox
  - wget https://googledrive.com/host/0B5VlNZ_Rvdw6NTJoZDBSVy1ZdkE -O $CHROME_SANDBOX
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
node_js:
  - "0.10"
script: "make ci"
after_script:
  - make coverage
sudo: false
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d55e363c3fc707460225
