language: node_js
cache:
  directories:
    - node_modules
    - bower_components
addons:
  apt:
    packages:
      - libcairo2-dev
      - libgif-dev
      - libjpeg8-dev
  firefox: "latest"
  googlechrome: "latest"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
node_js:
  - "0.10"
script: "make ci"
after_script:
  - make coverage
sudo: false
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d55e363c3fc707460225
